# apiVersion: v1
# kind PersistentVolumeClaim
# metadata:
#   name: postgres-pvc
# spec:
#   accessModes:
#     -ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi


---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16.3
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: env-config
        # - secretRef:
        #     name: env-secret
      #   volumeMounts:
      #   - mountPath: /var/lib/postgresql/data
      #     name: postgres-data
      # volumes:
      #   - name: postgres-data
      #     persistentVolumeClaim:
      #       claimName: postgres-pvc
