version: "3.8"
services:
  discord_db:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: on-failure
    env_file:
      - ./discord_bot/discord_db/.env
  
  grafana:
    image: grafana/grafana:11.1.0
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    env_file:
      - .env

volumes:
  grafana_data: